# Generated by Django 3.1.1 on 2024-09-09 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_year',
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default=2, max_length=100, verbose_name='Tên lớp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.class'),
        ),
    ]
