# Generated by Django 3.1.1 on 2024-09-09 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20240909_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.session'),
        ),
    ]
