# Generated by Django 3.1.1 on 2024-09-09 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20240909_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AddField(
            model_name='session',
            name='end_year',
            field=models.DateField(default='2025-9-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='start_year',
            field=models.DateField(default='2025-9-9'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
        ),
    ]
