# Generated by Django 3.1.1 on 2024-09-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20240909_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
    ]
